#!/bin/bash -l

# Submit job with the command: qsub rjob

# Set the runtime limit (default 12 hours):
#$ -l h_rt=24:00:00

# Specify your project
#$ -P jinglonggrp

# Give the job a name (default: script name)
#$ -N rjob

# Join the output and error streams
#$-j y



# Start 1000 tasks
#$ -t 1-1000

# Redirect job output files to a folder logs
#$ -o logs




# Fpr parallel jobs
#$ -pe omp 4

## end of qsub options

module load R/4.0.2
module load gurobi/9.1.1
Rscript Main_Nonlinear_LazyRun.R




